//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCrawler
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbGooglePR
    {
        public int Id { get; set; }
        public string Domain { get; set; }
        public Nullable<int> GooglePR { get; set; }
        public Nullable<int> BackLinks { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<bool> Dmoz { get; set; }
        public Nullable<bool> Archive { get; set; }
    }
}
