//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCrawler
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbSplit
    {
        public int Id { get; set; }
        public Nullable<int> DomID { get; set; }
        public string NameWords { get; set; }
        public string NameShown { get; set; }
        public Nullable<int> WordCount { get; set; }
    }
}
