//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdateData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDomainsFromSrc
    {
        public int Id { get; set; }
        public string Domain { get; set; }
        public string Name { get; set; }
        public string Tld { get; set; }
        public string Length { get; set; }
        public Nullable<int> Source { get; set; }
        public Nullable<int> Status { get; set; }
        public string IdInSource { get; set; }
        public string ExpDate { get; set; }
        public string Price { get; set; }
        public string Age { get; set; }
        public string SrcFile { get; set; }
    }
}
