//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdateData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbNewDomain
    {
        public string Domain { get; set; }
        public string Name { get; set; }
        public string Tld { get; set; }
        public Nullable<int> Source { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<float> ExpDate { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> Length { get; set; }
        public string Tags { get; set; }
        public int Id { get; set; }
        public Nullable<System.DateTime> ExpD { get; set; }
        public Nullable<int> Alexa { get; set; }
        public Nullable<int> Visits { get; set; }
        public Nullable<int> GooglePR { get; set; }
        public Nullable<int> BackLinks { get; set; }
        public Nullable<int> Year { get; set; }
        public string NameShown { get; set; }
        public string NameWords { get; set; }
        public Nullable<int> WordCount { get; set; }
        public Nullable<int> KeywordSearches { get; set; }
        public Nullable<int> Cpc { get; set; }
        public Nullable<int> Competition { get; set; }
        public Nullable<short> DB { get; set; }
        public Nullable<int> DFI { get; set; }
        public Nullable<bool> Dmoz { get; set; }
        public Nullable<bool> Archive { get; set; }
    }
}
