//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdateData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbSource
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> SrcFile { get; set; }
        public string SrcLink { get; set; }
        public string SrcSite { get; set; }
        public Nullable<int> Src { get; set; }
        public string SrcName { get; set; }
        public string Description { get; set; }
        public string Comments { get; set; }
        public string FullName { get; set; }
    }
}
